export enum ErrorCode {
  // Authentication errors
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS',

  // User errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_INVALID_DATA = 'USER_INVALID_DATA',

  // Room errors
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  ROOM_ACCESS_DENIED = 'ROOM_ACCESS_DENIED',
  ROOM_ALREADY_MEMBER = 'ROOM_ALREADY_MEMBER',
  ROOM_INVALID_CONFIG = 'ROOM_INVALID_CONFIG',

  // Message errors
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
  MESSAGE_INVALID_CONTENT = 'MESSAGE_INVALID_CONTENT',

  // Invitation errors
  INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  INVITATION_ALREADY_USED = 'INVITATION_ALREADY_USED',
  INVITATION_NOT_FOR_USER = 'INVITATION_NOT_FOR_USER',

  // AI errors
  AI_PROVIDER_ERROR = 'AI_PROVIDER_ERROR',
  AI_CONFIG_INVALID = 'AI_CONFIG_INVALID',
  AI_GENERATION_FAILED = 'AI_GENERATION_FAILED',

  // Attachment errors
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',
  ATTACHMENT_UPLOAD_FAILED = 'ATTACHMENT_UPLOAD_FAILED',
  ATTACHMENT_INVALID_TYPE = 'ATTACHMENT_INVALID_TYPE',

  // General errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
}
